[development]
[development.database]
host="127.0.0.1"
port=30302
user="some_user"
pass="some_pass"
db="some_db"

[development.server]
host="0.0.0.0"
port=30303

[production]
[production.database]
host="127.0.0.1"
port=30302
user="some_user"
pass="some_pass"
db="some_db"

[production.server]
host="0.0.0.0"
port=30303


[testing]
[testing.database]
host="127.0.0.1"
port=30302
user="some_user"
pass="some_pass"
db="some_db"

[testing.server]
host="127.0.0.1"
port=30303
