version: "3"

services:
    
  primary_db:
    image: postgres:alpine
    restart: always
    container_name: primary_db_dev
    environment:
      - POSTGRES_USER=some_user
      - POSTGRES_PASSWORD=some_pass
      - POSTGRES_DB=some_db
      - PGDATA=/var/lib/postgresql/data
    ports:
      - 30302:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data    
    networks: 
      - app-network

networks:
  app-network:
    driver: "bridge"


# Primarily only includes technologies vital to development
